version: '3.8'

services:
  app:
    image: python:3.11.7-slim-bookworm
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata
      - PYTHONPATH=/app
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G