version: '3.8'

services:
  app:
    container_name: fastapi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata
      - PYTHONPATH=/app
      - OMP_THREAD_LIMIT=2  # Оптимизация многопоточности Tesseract
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
