services:
  app:
    container_name: fastapi-app
    build:
      context: .
      args:
        - BUILD_VERSION
    ports:
      - "8000:8000"
    environment:
      - TESSDATA_PREFIX=/usr/share/tesseract-ocr/tessdata
      - PYTHONPATH=/app
      - OMP_THREAD_LIMIT=2